Repository nimblehq/sms-forwarder, pull requests merged in 2021-05, with the labels that each got.

#3 [Chore] Sync new git template
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug_template.md
  .github/ISSUE_TEMPLATE/chore_template.md
  .github/ISSUE_TEMPLATE/feature_template.md
  .github/pull_request_template.md
  LICENSE
  README.md
Labels: type : chore

#4 [Setup Project] App logo and application name
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/co/nimblehq/smsforwarder/SmsForwarderApplication.kt
  android/app/src/main/java/co/nimblehq/smsforwarder/di/modules/AppModule.kt
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_background.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_background.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_background.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_background.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_background.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
Labels: mobile, type : chore

#5 [Login] Initial Login UI
  android/app/src/main/java/co/nimblehq/smsforwarder/ui/base/NavigationEvent.kt
  android/app/src/main/java/co/nimblehq/smsforwarder/ui/screens/MainNavigator.kt
  android/app/src/main/java/co/nimblehq/smsforwarder/ui/screens/login/LoginFragment.kt
  android/app/src/main/java/co/nimblehq/smsforwarder/ui/screens/login/LoginViewModelImpl.kt
  android/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  android/app/src/main/res/drawable-xxhdpi/ic_sms.webp
  android/app/src/main/res/drawable/bg_login.xml
  android/app/src/main/res/drawable/ic_launcher_background.xml
  android/app/src/main/res/layout/activity_main.xml
  android/app/src/main/res/layout/fragment_login.xml
  android/app/src/main/res/navigation/nav_graph_main.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/dimens.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/styles.xml
Labels: mobile, type : feature

#6 [Integrate] As a user, I need to grant PERMISSION to allow the app to read the incoming messages
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/co/nimblehq/smsforwarder/ui/screens/home/HomeFragment.kt
  android/app/src/main/res/values/strings.xml
Labels: mobile, type : feature

#8 [API] Add forward sms api to send email
  web/api/api-ext.js
  web/api/app.js
  web/app.js
  web/config/config.json
  web/deploy_heroku.sh
  web/package.json
  web/services/mailer.js
  web/views/mailer/forgot-password/html.pug
Labels: api, type : feature

#7 [UI] Home screen
  android/app/src/main/java/co/nimblehq/smsforwarder/ui/base/BaseFragment.kt
  android/app/src/main/java/co/nimblehq/smsforwarder/ui/screens/home/HomeFragment.kt
  android/app/src/main/java/co/nimblehq/smsforwarder/ui/screens/home/HomeViewModel.kt
  android/app/src/main/java/co/nimblehq/smsforwarder/ui/screens/home/SmsAdapter.kt
  android/app/src/main/java/co/nimblehq/smsforwarder/ui/screens/login/LoginFragment.kt
  android/app/src/main/java/co/nimblehq/smsforwarder/ui/screens/second/SecondBundle.kt
  android/app/src/main/java/co/nimblehq/smsforwarder/ui/screens/second/SecondFragment.kt
  android/app/src/main/java/co/nimblehq/smsforwarder/ui/screens/second/SecondViewModel.kt
  android/app/src/main/res/drawable/bg_app.xml
  android/app/src/main/res/drawable/bg_circle_button.xml
  android/app/src/main/res/drawable/bg_home.xml
  android/app/src/main/res/drawable/bg_item_bullet.xml
  android/app/src/main/res/layout/fragment_home.xml
  android/app/src/main/res/layout/fragment_login.xml
  android/app/src/main/res/layout/item_data.xml
  android/app/src/main/res/layout/item_sms.xml
  android/app/src/main/res/values/dimens.xml
  android/app/src/main/res/values/dimens_text.xml
  android/app/src/main/res/values/strings.xml
  android/domain/src/main/java/co/nimblehq/smsforwarder/domain/data/Sms.kt
  android/domain/src/main/java/co/nimblehq/smsforwarder/domain/repository/ApiRepository.kt
  android/domain/src/main/java/co/nimblehq/smsforwarder/domain/test/MockUtil.kt
  android/domain/src/main/java/co/nimblehq/smsforwarder/domain/usecase/GetExampleDataUseCase.kt
Labels: mobile, type : feature
